on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install chez
      run: |
        sudo apt install -y chezscheme chezscheme-dev uuid-dev
    - name: Compile main.ss
      run: |
        export SCHEME_DIRS=$(echo /usr/lib/csv*/ta6le/)
        ./compile.ss ./main.ss
    - name: Run result
      run: |
        ldd ./main
        ./main

